Enable travis, etc
dart-lang/package_resolver pull request #6
Opened 2017-07-13 00:51 UTC by kevmoo

2017-07-13 00:57 UTC, nex3 requested changes

2017-07-13 00:57 UTC, nex3 commented on .travis.yml
> +  - 1.22.1
I don't think it's worth testing more than dev or stable here. It'll just add to the iteration time without any substantial gain.

2017-07-13 00:57 UTC, nex3 commented on .travis.yml
> +      dart_task: dartfmt
Why is this in `allow_failures`?

2017-07-13 00:57 UTC, nex3 commented on .travis.yml
> +dart_task:
It's probably overkill to run these in three separate builders; this package doesn't have that many tests.

2017-07-13 00:57 UTC, nex3 commented on analysis_options.yaml
> +  rules:
Lints give me hives; they aren't well-curated or -maintained in general. If I were very confident in an individual lint I'd be okay with enabling it, but this scattershot approach makes me worried that we'll end up chasing down false positives and bugs.

2017-07-13 00:57 UTC, nex3 commented on analysis_options.yaml
> +    dead_code: error
Why are these upgraded to errors?

2017-07-13 02:23 UTC, kevmoo commented on analysis_options.yaml
> +    dead_code: error
They cause errors in Google3 – staying consistent.

2017-07-13 02:23 UTC, kevmoo commented on analysis_options.yaml
> +  rules:
These are the ones we use on angular – and google3.

They are used a lot internally. Pretty standard set.

2017-07-13 02:23 UTC, kevmoo commented on .travis.yml
> +  - 1.22.1
Fixed

2017-07-13 02:24 UTC, kevmoo commented on .travis.yml
> +dart_task:
With a smaller matrix, it makes debugging pretty easy.

2017-07-13 20:19 UTC, kevmoo commented
@nex3 PTAL?

2017-07-13 22:42 UTC, nex3 requested changes

2017-07-13 22:42 UTC, nex3 commented on test/current_isolate_info_test.dart
> +@TestOn('vm')
Nit: newline above

2017-07-13 22:42 UTC, nex3 commented on analysis_options.yaml
> +    dead_code: error
Why does Google3 config control which hints are upgraded in third-party packages?

2017-07-13 22:42 UTC, nex3 commented on analysis_options.yaml
> +  rules:
That's fine for them, but I'd prefer to leave these off of my packages.

2017-07-13 22:42 UTC, nex3 commented on test/package_config_info_test.dart
> +    }, onPlatform: {'!vm': new Skip()});
You should never commit a skip without a description.

If this test isn't compatible with the browser, you should use `testOn: "vm"`, not a skip. Skips are for tests that are broken and need to be fixed.

Same below.

2017-07-14 19:29 UTC, kevmoo commented
`runOn` fixed. 

Lints removed – although they are a great way to enforce style and to avoid common mistakes in code. They also help us guide contributors through PRs by highlighting common mistakes.

2017-07-14 22:47 UTC, nex3 commented on .travis.yml
> +dart_task:
That's true, but it also decreases throughput and soaks up builders that other packages may need.

2017-07-15 02:48 UTC, merged